// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211218215255_AddedPostModel")]
    partial class AddedPostModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Shared.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1001,
                            Content = "Descriprion for test data one",
                            Thumbnail = "./uploads/placeholder.jpg",
                            Title = "Test Data One"
                        },
                        new
                        {
                            SkillId = 1002,
                            Content = "Descriprion for test data two",
                            Thumbnail = "./uploads/placeholder.jpg",
                            Title = "Test Data Two"
                        },
                        new
                        {
                            SkillId = 1003,
                            Content = "Descriprion for test data three",
                            Thumbnail = "./uploads/placeholder.jpg",
                            Title = "Test Data Three"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
