// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211219043248_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Shared.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Content = "Descriprion for test data 1",
                            Created_At = new DateTime(2021, 12, 19, 5, 32, 48, 28, DateTimeKind.Local).AddTicks(3511),
                            Thumbnail = "./uploads/placeholder.jpg",
                            Title = "Test Data 1",
                            Updated_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BlogId = 2,
                            Content = "Descriprion for test data 2",
                            Created_At = new DateTime(2021, 12, 19, 5, 32, 48, 28, DateTimeKind.Local).AddTicks(3550),
                            Thumbnail = "./uploads/placeholder.jpg",
                            Title = "Test Data 2",
                            Updated_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BlogId = 3,
                            Content = "Descriprion for test data 3",
                            Created_At = new DateTime(2021, 12, 19, 5, 32, 48, 28, DateTimeKind.Local).AddTicks(3554),
                            Thumbnail = "./uploads/placeholder.jpg",
                            Title = "Test Data 3",
                            Updated_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
